#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" during the 9th

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
